import type { IconType } from "react-icons";
import {
  SiReact,
  SiNextdotjs,
  SiTypescript,
  SiJavascript,
  SiTailwindcss,
  SiHtml5,
  SiCss,
  SiFramer,
  SiThreedotjs,
  SiUnity,
  SiGit,
  SiGithub,
  SiFigma,
  SiNetlify,
  SiBlender,
  SiPython,
  SiWebgl,
  SiP5Dotjs,
  SiAutodeskmaya,
} from "react-icons/si";
import { VscVscode } from "react-icons/vsc";

export const techIcons: Record<string, IconType | undefined> = {
  React: SiReact,
  "Next.js": SiNextdotjs,
  TypeScript: SiTypescript,
  JavaScript: SiJavascript,
  "Tailwind CSS": SiTailwindcss,
  HTML: SiHtml5,
  CSS: SiCss,
  "Framer Motion": SiFramer,
  "Three.js": SiThreedotjs,
  Unity: SiUnity,
  Git: SiGit,
  GitHub: SiGithub,
  Figma: SiFigma,
  Netlify: SiNetlify,
  Blender: SiBlender,
  Python: SiPython,
  WebGL: SiWebgl,
  "p5.js": SiP5Dotjs,
  Maya: SiAutodeskmaya,
  "VS Code": VscVscode,
};